complete -c rnr -n "__fish_use_subcommand" -s l -l replace-limit -d 'Limit of replacements, all matches if set to 0'
complete -c rnr -n "__fish_use_subcommand" -l color -d 'Set color output mode' -r -f -a "always auto never"
complete -c rnr -n "__fish_use_subcommand" -s d -l max-depth -d 'Set max depth in recursive mode'
complete -c rnr -n "__fish_use_subcommand" -s n -l dry-run -d 'Only show what would be done (default mode)'
complete -c rnr -n "__fish_use_subcommand" -s f -l force -d 'Make actual changes to files'
complete -c rnr -n "__fish_use_subcommand" -s b -l backup -d 'Generate file backups before renaming'
complete -c rnr -n "__fish_use_subcommand" -s s -l silent -d 'Do not print any information'
complete -c rnr -n "__fish_use_subcommand" -l dump -d 'Force dumping operations into a file even in dry-run mode'
complete -c rnr -n "__fish_use_subcommand" -l no-dump -d 'Do not dump operations into a file'
complete -c rnr -n "__fish_use_subcommand" -s D -l include-dirs -d 'Rename matching directories'
complete -c rnr -n "__fish_use_subcommand" -s r -l recursive -d 'Recursive mode'
complete -c rnr -n "__fish_use_subcommand" -s x -l hidden -d 'Include hidden files and directories'
complete -c rnr -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c rnr -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c rnr -n "__fish_use_subcommand" -f -a "from-file" -d 'Read operations from a dump file'
complete -c rnr -n "__fish_use_subcommand" -f -a "to-ascii" -d 'Replace file name UTF-8 chars with ASCII chars representation.'
complete -c rnr -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c rnr -n "__fish_seen_subcommand_from from-file" -l color -d 'Set color output mode' -r -f -a "always auto never"
complete -c rnr -n "__fish_seen_subcommand_from from-file" -s n -l dry-run -d 'Only show what would be done (default mode)'
complete -c rnr -n "__fish_seen_subcommand_from from-file" -s f -l force -d 'Make actual changes to files'
complete -c rnr -n "__fish_seen_subcommand_from from-file" -s b -l backup -d 'Generate file backups before renaming'
complete -c rnr -n "__fish_seen_subcommand_from from-file" -s s -l silent -d 'Do not print any information'
complete -c rnr -n "__fish_seen_subcommand_from from-file" -l dump -d 'Force dumping operations into a file even in dry-run mode'
complete -c rnr -n "__fish_seen_subcommand_from from-file" -l no-dump -d 'Do not dump operations into a file'
complete -c rnr -n "__fish_seen_subcommand_from from-file" -s u -l undo -d 'Undo the operations from the dump file'
complete -c rnr -n "__fish_seen_subcommand_from from-file" -s h -l help -d 'Prints help information'
complete -c rnr -n "__fish_seen_subcommand_from from-file" -s V -l version -d 'Prints version information'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -l color -d 'Set color output mode' -r -f -a "always auto never"
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -s d -l max-depth -d 'Set max depth in recursive mode'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -s n -l dry-run -d 'Only show what would be done (default mode)'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -s f -l force -d 'Make actual changes to files'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -s b -l backup -d 'Generate file backups before renaming'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -s s -l silent -d 'Do not print any information'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -l dump -d 'Force dumping operations into a file even in dry-run mode'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -l no-dump -d 'Do not dump operations into a file'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -s D -l include-dirs -d 'Rename matching directories'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -s r -l recursive -d 'Recursive mode'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -s x -l hidden -d 'Include hidden files and directories'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -s h -l help -d 'Prints help information'
complete -c rnr -n "__fish_seen_subcommand_from to-ascii" -s V -l version -d 'Prints version information'
complete -c rnr -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c rnr -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
