#!/bin/bash

if ! -f ~/.vim/autoload/plug.vim; then
	echo "Installing vim-plug in Vim"
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if ! -f "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim; then
	echo "Installing vim-plug in Neovim"
	curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi

if command -v vim >/dev/null 2>&1; then
	echo "Bootstraping Vim"
	vim '+PlugInstall' '+PlugClean!' '+PlugUpdate' '+qall'
fi

if command -v nvim >/dev/null 2>&1; then
	echo "Bootstraping Neovim"
	nvim '+PlugInstall' '+PlugClean!' '+PlugUpdate' '+qall'
fi

