#!/bin/bash

if [[ ! -f ~/.vim/autoload/plug.vim ]]; then
	echo "Installing vim-plug in Vim"
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [[ ! -f "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim ]]; then
	echo "Installing vim-plug in Neovim"
	curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if command -v vim >/dev/null 2>&1; then
	echo "Bootstraping Vim"
	vim '+PlugInstall' '+PlugClean!' '+PlugUpdate' '+qall'
fi

if command -v nvim >/dev/null 2>&1; then
	echo "Bootstraping Neovim"
	nvim '+PlugInstall' '+PlugClean!' '+PlugUpdate' '+qall'
fi

if ! command -v rustc >/dev/null 2>&1; then
	if ! command -v rustup >/dev/null 2>&1; then
		echo "Installing rust"
		curl https://sh.rustup.rs -sSf | sh -s -- --profile default --default-toolchain stable
		rustup completions zsh > ~/.zsh/completions/_rustup
	fi
fi

if command -v bat >/dev/null 2>&1; then
	if [[ ! -f .cache/bat/themes.bin ]]; then
		echo "Building cache for bat themes,sytaxes,etc"
		bat cache --build
	fi
fi

if command -v starship >/dev/null 2>&1; then
	starship completions zsh > ~/.zsh/completions/_starship
fi

if command -v fish >/dev/null 2>&1; then
	fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
	fish -c 'fisher install (cat ~/.config/fish/fisher_plugins)'
fi
